spring.application.name=ChatApp
spring.datasource.url=jdbc:postgresql://localhost:5432/chatapp
spring.datasource.username= Louis
spring.datasource.password= louis@2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect